# Generated by Django 2.2.1 on 2019-05-13 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.CharField(max_length=20)),
                ('product1_id', models.CharField(max_length=20)),
                ('product2_id', models.CharField(max_length=20)),
                ('product3_id', models.CharField(max_length=20)),
                ('pub_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
