# Generated by Django 2.2.1 on 2019-05-18 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopeeSite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopinfo',
            old_name='product1_id',
            new_name='product1id',
        ),
        migrations.RenameField(
            model_name='shopinfo',
            old_name='product2_id',
            new_name='product2id',
        ),
        migrations.RenameField(
            model_name='shopinfo',
            old_name='product3_id',
            new_name='product3id',
        ),
        migrations.RenameField(
            model_name='shopinfo',
            old_name='shop_id',
            new_name='shopid',
        ),
    ]
